[package]
name = "cubes-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.8"
crossbeam-queue = "0.3"
rand = "0.8.5"
chrono = "0.4.31"
flate2 = "1.0.28"
